name: hypnos
description: "Ambient noise app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  markdown_widget: ^2.3.2+8
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: #000000
    theme_color: #000000
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"